name: Bug report / 报告运行错误或异常
description: 提交关于错误或异常的报告以帮助我们改进 / Submit a report about errors or exceptions to help us improve
title: "[Bug]: "
labels: [ bug ]
body:
  - type: checkboxes
    attributes:
      label: 不要跳过这些步骤 / Don't skip these steps
      description: 提交问题前，请仔细完成以下步骤 / Carefully complete the following steps before submitting an issue
      options:
        - label: 我明白，如果我“故意”删除或跳过任何强制性的\*字段，我将被**封锁** / I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
          required: true
        - label: 我已经通过搜索仔细检查过没有存在已经创建的相似问题 / I have checked through the search that there are no similar issues that already exist
          required: true
        - label: 我不会提交任何与本项目无关的问题 / I will not submit any issues that are not related to this project
          required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: 触发环境 / Occurrence environment
      description: |
        选择该Bug触发于什么环境 / Select what environment is the Bug triggered in:
      options:
        - label: 工作流 / Workflow
          required: false
        - label: 软件 / GUI
          required: false
        - label: Docker
          required: false
          on_select:
            - type: checkboxes
              id: docker_options
              attributes:
                label: 镜像架构 / Image architecture
                description: |
                  选择镜像的架构 / Select the architecture of the image:
                options:
                  - label: AMD64
                    required: false
                  - label: ARM64
                    required: false
                  - label: ARM V7
                    required: false
        - label: 命令行 / Command line
          required: false
  - type: textarea
    id: description
    attributes:
      label: 具体描述 / Bug description
      description: 对于Bug的具体描述，好的描述有助于理解和解决 / As for the specific description of the Bug, a good description will help to understand and solve it
      placeholder: 提供任何附加信息，任何建议的解决方案，以及尽可能多的上下文和示例 / Provide any additional information, any suggested solutions, and as much context and examples as possible
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: 报错日志 / Error log
      description: 提供Bug的详细报错日志，尽量复制文本或上传文件，不要截图 / Provide detailed error logs of bugs, copy text or upload files as much as possible, do not take screenshots
      placeholder: Please enter a detailed error log
    validations:
      required: false
